import React from 'react';
export const exercisesDetails = () => <div>exercises distinct</div>;
export const exercises_detail_0 = (p:any)=> <div>exercises 0 cloze</div>;
export const exercises_detail_1 = (p:any)=> <div>exercises 1 multiple choice</div>;
export const exercises_detail_2 = (p:any)=> <div>exercises 2 dictation</div>;
export const exercises_detail_3 = (p:any)=> <div>exercises 3 shadowing</div>;
export const exercises_detail_4 = (p:any)=> <div>exercises 4 cloze</div>;
export const exercises_detail_5 = (p:any)=> <div>exercises 5 multiple choice</div>;
export const exercises_detail_6 = (p:any)=> <div>exercises 6 dictation</div>;
export const exercises_detail_7 = (p:any)=> <div>exercises 7 shadowing</div>;
export const exercises_detail_8 = (p:any)=> <div>exercises 8 cloze</div>;
export const exercises_detail_9 = (p:any)=> <div>exercises 9 multiple choice</div>;
export const exercises_detail_10 = (p:any)=> <div>exercises 10 dictation</div>;
export const exercises_detail_11 = (p:any)=> <div>exercises 11 shadowing</div>;
export const exercises_detail_12 = (p:any)=> <div>exercises 12 cloze</div>;
export const exercises_detail_13 = (p:any)=> <div>exercises 13 multiple choice</div>;
export const exercises_detail_14 = (p:any)=> <div>exercises 14 dictation</div>;
export const exercises_detail_15 = (p:any)=> <div>exercises 15 shadowing</div>;
export const exercises_detail_16 = (p:any)=> <div>exercises 16 cloze</div>;
export const exercises_detail_17 = (p:any)=> <div>exercises 17 multiple choice</div>;
export const exercises_detail_18 = (p:any)=> <div>exercises 18 dictation</div>;
export const exercises_detail_19 = (p:any)=> <div>exercises 19 shadowing</div>;