import React from 'react';
export const communityDetails = () => <div>community distinct</div>;
export const community_detail_0 = (p:any)=> <div>community 0 discussions</div>;
export const community_detail_1 = (p:any)=> <div>community 1 corrections</div>;
export const community_detail_2 = (p:any)=> <div>community 2 peer review</div>;
export const community_detail_3 = (p:any)=> <div>community 3 discussions</div>;
export const community_detail_4 = (p:any)=> <div>community 4 corrections</div>;
export const community_detail_5 = (p:any)=> <div>community 5 peer review</div>;
export const community_detail_6 = (p:any)=> <div>community 6 discussions</div>;
export const community_detail_7 = (p:any)=> <div>community 7 corrections</div>;
export const community_detail_8 = (p:any)=> <div>community 8 peer review</div>;
export const community_detail_9 = (p:any)=> <div>community 9 discussions</div>;
export const community_detail_10 = (p:any)=> <div>community 10 corrections</div>;
export const community_detail_11 = (p:any)=> <div>community 11 peer review</div>;
export const community_detail_12 = (p:any)=> <div>community 12 discussions</div>;
export const community_detail_13 = (p:any)=> <div>community 13 corrections</div>;
export const community_detail_14 = (p:any)=> <div>community 14 peer review</div>;
export const community_detail_15 = (p:any)=> <div>community 15 discussions</div>;
export const community_detail_16 = (p:any)=> <div>community 16 corrections</div>;
export const community_detail_17 = (p:any)=> <div>community 17 peer review</div>;
export const community_detail_18 = (p:any)=> <div>community 18 discussions</div>;
export const community_detail_19 = (p:any)=> <div>community 19 corrections</div>;