import React from 'react';
export const vocabularyDetails = () => <div>vocabulary distinct</div>;
export const vocabulary_detail_0 = (p:any)=> <div>vocabulary 0 word bank</div>;
export const vocabulary_detail_1 = (p:any)=> <div>vocabulary 1 SRS</div>;
export const vocabulary_detail_2 = (p:any)=> <div>vocabulary 2 flashcards</div>;
export const vocabulary_detail_3 = (p:any)=> <div>vocabulary 3 Leitner</div>;
export const vocabulary_detail_4 = (p:any)=> <div>vocabulary 4 word bank</div>;
export const vocabulary_detail_5 = (p:any)=> <div>vocabulary 5 SRS</div>;
export const vocabulary_detail_6 = (p:any)=> <div>vocabulary 6 flashcards</div>;
export const vocabulary_detail_7 = (p:any)=> <div>vocabulary 7 Leitner</div>;
export const vocabulary_detail_8 = (p:any)=> <div>vocabulary 8 word bank</div>;
export const vocabulary_detail_9 = (p:any)=> <div>vocabulary 9 SRS</div>;
export const vocabulary_detail_10 = (p:any)=> <div>vocabulary 10 flashcards</div>;
export const vocabulary_detail_11 = (p:any)=> <div>vocabulary 11 Leitner</div>;
export const vocabulary_detail_12 = (p:any)=> <div>vocabulary 12 word bank</div>;
export const vocabulary_detail_13 = (p:any)=> <div>vocabulary 13 SRS</div>;
export const vocabulary_detail_14 = (p:any)=> <div>vocabulary 14 flashcards</div>;
export const vocabulary_detail_15 = (p:any)=> <div>vocabulary 15 Leitner</div>;
export const vocabulary_detail_16 = (p:any)=> <div>vocabulary 16 word bank</div>;
export const vocabulary_detail_17 = (p:any)=> <div>vocabulary 17 SRS</div>;
export const vocabulary_detail_18 = (p:any)=> <div>vocabulary 18 flashcards</div>;
export const vocabulary_detail_19 = (p:any)=> <div>vocabulary 19 Leitner</div>;